apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       - name: web
         image: lukasheinrich/cap_web
         ports:
          - containerPort: 5000 
            name: "http"
         imagePullPolicy: Always
