apiVersion: v1
kind: Service
metadata:
  name: yadage-atlas-service
spec:
  type: "NodePort"
  ports:
  - port: 80
    targetPort: 8888
    name: "http"
    protocol: TCP
  selector:
    app: yadage-atlas-worker
